CREATE TABLE USERLIST(
	
	id INTEGER,
	username VARCHAR(255),
	email VARCHAR(255)
);

CREATE TABLE PRODUCTS(

	PRODUCT_ID INTEGER,
	PRODUCT_NAME VARCHAR(255),
	PRODUCT_PRICE FLOAT
	
	
);


INSERT INTO USERLIST (id,username,email) VALUES (1,'test', 'test.test@gmail.com');
INSERT INTO USERLIST (id,username,email) VALUES (2,'Pratik', 'pratik.r@gmail.com');
INSERT INTO USERLIST (id,username,email) VALUES (3,'rohan', 'rohan.s@gmail.com');
INSERT INTO USERLIST (id,username,email) VALUES (4,'gamerboy', 'gamerboy1@gmail.com');
INSERT INTO USERLIST (id,username,email) VALUES (4,'samsung', 'sam2@gmail.com');




INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES (1,'Milk', 20.5);
INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES (2,'Bread', 30);
INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES (3,'Rice', 60);
INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES (4,'Wheat', 110);
INSERT INTO PRODUCTS (PRODUCT_ID,PRODUCT_NAME,PRODUCT_PRICE) VALUES (4,'Sugar', 40);

SELECT * FROM USERLIST;
SELECT * FROM PRODUCTS;